#! /bin/bash


./makeShared


mkdir ./ServerJava/classes 2> test.txt
rm test.txt


javac -d ./ServerJava/classes -cp $CLASSPATH:./SharedFiles/:./ServerJava/classes/ ./ServerJava/Communications/ReceiveCommunicationsServer.java
javac -d ./ServerJava/classes -cp $CLASSPATH:./SharedFiles/:./ServerJava/classes/ ./ServerJava/Communications/SendCommunicationsServer.java

javac -d ./ServerJava/classes -cp $CLASSPATH:./SharedFiles/:./ServerJava/classes/ ./ServerJava/authenticationServer.java
javac -d ./ServerJava/classes -cp $CLASSPATH:./SharedFiles/:./ServerJava/classes/ ./ServerJava/Server.java

java -cp $CLASSPATH:./ServerJava/classes Client

rm ./ServerJava/classes *.class
rm ./SharedFiles/classes *.class


#adds a 1 minute delay
#read -rsp $'Press any key or wait 1 minute to continue...\n' -n 1 -t 60;
